Fixed. test is failed on Ruby 3.0+
```
  1) Error:
LargeGemListSpec#test_method: more than 5 versions of the same gem :
ArgumentError: wrong number of arguments (given 2, expected 0..1)
    /Users/sue445/workspace/github.com/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-3.35.3/lib/capybara/rack_test/node.rb:67:in `click'
    /Users/sue445/workspace/github.com/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-3.35.3/lib/capybara/rack_test/node.rb:131:in `call'
    /Users/sue445/workspace/github.com/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-3.35.3/lib/capybara/rack_test/node.rb:131:in `click'
    /Users/sue445/workspace/github.com/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-mechanize-1.11.0/lib/capybara/mechanize/node.rb:12:in `click'
    /Users/sue445/workspace/github.com/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-3.35.3/lib/capybara/node/element.rb:172:in `block in click'
    /Users/sue445/workspace/github.com/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-3.35.3/lib/capybara/node/element.rb:597:in `block in perform_click_action'
    /Users/sue445/workspace/github.com/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-3.35.3/lib/capybara/node/base.rb:83:in `synchronize'
    /Users/sue445/workspace/github.com/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-3.35.3/lib/capybara/node/element.rb:597:in `perform_click_action'
    /Users/sue445/workspace/github.com/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-3.35.3/lib/capybara/node/element.rb:171:in `click'
    /Users/sue445/workspace/github.com/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-3.35.3/lib/capybara/node/actions.rb:42:in `click_link'
    /Users/sue445/workspace/github.com/geminabox/geminabox/vendor/bundle/ruby/3.0.0/gems/capybara-3.35.3/lib/capybara/session.rb:762:in `click_link'
    /Users/sue445/workspace/github.com/geminabox/geminabox/test/integration/web_interface/large_gem_list_test.rb:32:in `block in <class:LargeGemListSpec>'

```

c.f. https://github.com/jeroenvandijk/capybara-mechanize/issues/68

(cherry picked from commit 4fa2f7afd37afdf28ced955fce1d14ff7be31c56)