Fix http_proxy env variable useage
Not sure how the person submitting the patch to use the http_proxy
environment variable every had things working because

    irb(main):001:0> ENV['http_proxy'].empty?
    NoMethodError: undefined method `empty?' for nil:NilClass